#!/usr/bin/env bash

# Titulo: Instalación mínima del entorno de escritorio mínimo Budgie (similar a gnome pero sin shell).
# Autor: Héctor Iván Vega Zamudio
# Correo: mxhectorvega@gmail.com
# Link: https://github.com/mxhectorvega
# Versión: 1.0
# Fecha de actualización 19/03/2023
# Nota: El sistema de preferencia debe haber sido instalado con la
# herramienta archinstall del liveUSB, seleccionando el perfil mínimo.

# Actualización
sudo pacman -Syyu --noconfirm

# Internos para el SO
sudo pacman -S usbutils ntfs-3g flatpak pacman-contrib xdg-user-dirs --noconfirm --needed
# Para ejecutar desde la terminal
sudo pacman -S git make gcc curl wget htop vim fuse less man --noconfirm --needed 

# Repo chaotic
sudo pacman -Syyu --noconfirm
sudo pacman-key --recv-key FBA220DFC880C036 --keyserver keyserver.ubuntu.com
sudo pacman-key --lsign-key FBA220DFC880C036
sudo pacman -U 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst' 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst' --noconfirm
sudo tee -a /etc/pacman.conf <<EOF
[chaotic-aur]
Include = /etc/pacman.d/chaotic-mirrorlist
EOF

# Paru
cd ; git clone https://aur.archlinux.org/paru-bin.git ; cd paru-bin ; makepkg -si --noconfirm ; cd ; rm -rf paru-bin
sudo sed -i "s/#BottomUp/BottomUp/g" /etc/paru.conf

# Actualización
sudo pacman -Syyu --noconfirm

# Instalando paquetes para escritorio BUDGIE
sudo pacman -S gnome-terminal budgie-desktop budgie-extras gnome-screenshot --noconfirm

# Display manager (pantalla de inicio de sesión)
sudo pacman -S lightdm lightdm-gtk-greeter --noconfirm

# Thunar extras
sudo pacman -S gvfs thunar thunar-archive-plugin thunar-volman thunar-archive-plugin tumbler ffmpegthumbnailer xarchiver zip unzip unrar unarj p7zip lzop lzip lrzip lha cpio arj --noconfirm --needed


# Instalando paquetes adicionales para el usuario
sudo pacman -S clipit --noconfirm

# habilitando bluetooth
sudo systemctl enable --now bluetooth.service

# Habilitando servicio de pantalla de inicio de sesión
sudo systemctl enable --now lightdm

# Mensaje final
sleep 1
printf '\n\n\tContribuye:\n\tmxhectorvega.ml\n\n\n'
sleep 1

# Habilitando servicio de pantalla de inicio de sesión
clear
printf '\n \nActivando display manager...\n'
sleep 1
sudo systemctl enable --now lightdm

