#!/bin/sh

#Instalar las dependencias al toque para flojos.
mkdir ~/.local ; mkdir ~/.local/share ; mkdir ~/.local/share/applications ; git clone https://github.com/mxhectorvega/dotfilesarchlinux ~/dotfilesarchlinux/ ; cp -R ~/dotfilesarchlinux/.local/* ~/.local ; cp ~/dotfilesarchlinux/.bashrc ~/.bashrc ; cp ~/dotfilesarchlinux/.xprofile ~/.xprofile ; cd ; rm -rf ~/dotfilesarchlinux ; sudo pacman -S python3 python-pip materia-gtk-theme materia-kde papirus-icon-theme bc tmux imagemagick ueberzug ffmpegthumbnailer feh mpd mpc ncmpcpp telegram-desktop htop bashtop xarchiver leafpad ranger pcmanfm sxiv zathura zathura-pdf-mupdf neovim mpv screenkey --noconfirm --needed ; yay -S gnome-shell-extension-dash-to-dock gnome-shell-extension-pop-shell-git gnome-shell-extension-dynamic-panel-transparency-git google-chrome-dev chrome-gnome-shell --noconfirm --needed
clear
