#!/bin/sh

#Instalar las dependencias al toque para flojos.
git clone https://github.com/mxhectorvega/st ~/st/ ; sudo make install ; mkdir ~/.local ; mkdir ~/.local/share ; mkdir ~/.local/share/applications ; git clone https://github.com/mxhectorvega/dofilesarchlinux ~/dofilesarchlinux/ ; cp ~/dofilesarchlinux/.local/share/applications/st.desktop ~/.local/share/applications/st.desktop ; cp ~/dofilesarchlinux/.bashrc ~/.bashrc ; cp ~/dofilesarchlinux/.xprofile ~/.xprofile ; rm -rf ~/dofilesarchlinux ; rm -rf ~/st ; cd ; sudo pacman -S materia-gtk-theme materia-kde papirus-icon-theme bc tmux imagemagick ueberzug ffmpegthumbnailer feh mpd mpc ncmpcpp telegram-desktop htop bashtop xarchiver leafpad ranger pcmanfm sxiv zathura zathura-pdf-mupdf neovim mpv screenkey --noconfirm --needed ; yay -S gnome-shell-extension-dash-to-dock gnome-shell-extension-pop-shell-git gnome-shell-extension-dynamic-panel-transparency-git google-chrome-dev chrome-gnome-shell --noconfirm --needed
clear
