#!/bin/sh

#Instalar las dependencias al toque para flojos.
sudo pacman -S materia-gtk-theme materia-kde papirus-icon-theme bc tmux imagemagick ueberzug ffmpegthumbnailer feh mpd mpc ncmpcpp slock telegram-desktop htop xarchiver neofetch leafpad ranger pcmanfm lxappearance dunst maim xclip sxiv xdotool calcurse zathura zathura-pdf-mupdf neovim mpv screenkey --noconfirm --needed

clear
