#!/usr/bin/env bash

# Instalación drivers para computadoras AMD y WIFI USB Wifi (TP-Link AC600 wireless Realtek RTL8811AU [Archer T2U Nano]).
# Repositorio: https://github.com/mxhectorvega/installarch
# Ejecución: curl -L is.gd/mxdrivers | bash
# Fecha de actualización: 05/02/2025
# Versión: 1.0

# Función para mostrar mensajes con formato
imprimir_mensaje() {
    local mensaje="$1"
    echo -e "\n\n\n\n\n\n\n\n\t\t\t\t\t\t\t$mensaje\n\n\n\n\n\n\n\n\n\n"
    sleep 3
}

# Actualización
sudo pacman -Sy --noconfirm

# Driver bluetooth
sudo pacman -S bluez bluez-utils --noconfirm --needed

# habilitando bluetooth
sudo systemctl enable --now bluetooth.service

# DRIVER AMDGPU 
sudo pacman -S xf86-video-amdgpu --noconfirm --needed

# VULKAN
sudo pacman -S vulkan-radeon lib32-vulkan-radeon  --noconfirm --needed

# OPENCL
sudo pacman -S opencl-mesa --noconfirm --needed

# VDPAU
sudo pacman -S libva-mesa-driver lib32-libva-mesa-driver mesa-vdpau lib32-mesa-vdpau --noconfirm --needed

# Instalando driver USB Wifi (TP-Link AC600 wireless Realtek RTL8811AU [Archer T2U Nano])
paru -S rtl88xxau-aircrack-dkms-git --noconfirm --needed

# Mensaje final
imprimir_mensaje "♥️ Suscríbete!\n\n\t\t\t\t\t\t\t🌐 https://www.youtube.com/mxhectorvega"
