#!/usr/bin/env bash

# Descripcion: Instalacion de paquetes flatpak.
# Fecha de actualizacion: 26/11/2023
# Nota: Requiere del paquete flatpak para poderse instalar.

# Actualziacion
sudo pacman -Syyu --noconfirm

sudo pacmab -S flatpak --noconfirm --needed

# Software personal en flatpak
flatpak install -y \
com.github.KRTirtho.Spotube \
com.github.gabutakut.gabutdm \
com.github.iwalton3.jellyfin-media-player \
com.github.tchx84.Flatseal \
com.hunterwittenborn.Celeste \
com.mattjakeman.ExtensionManager \
com.obsproject.Studio \
com.valvesoftware.Steam \
fr.handbrake.ghb \
io.github.celluloid_player.Celluloid \
io.itch.itch \
io.missioncenter.MissionCenter \
net.brinkervii.grapejuice \
net.davidotek.pupgui2 \
net.minetest.Minetest \
org.audacityteam.Audacity \
org.fedoraproject.MediaWriter \
org.gimp.GIMP \
org.jdownloader.JDownloader \
org.kde.kdenlive \
org.libreoffice.LibreOffice \
org.mozilla.Thunderbird \
org.mozilla.firefox \
org.pipewire.Helvum \
org.ryujinx.Ryujinx \
org.supertuxproject.SuperTux \
org.telegram.desktop

# para sacar la lista de apps:
# flatpak list --app --columns=application

# Mensaje final
printf '\n\n\tContribuye:\n\tmxhectorvega.com\n\n\n'