#!/usr/bin/env bash

# Descripcion: Instalacion de paquetes flatpak.
# Fecha de actualizacion: 12/05/2024
# Nota: Requiere del paquete flatpak para poderse instalar.

# Actualziacion
sudo pacman -Syyu --noconfirm

sudo pacmab -S flatpak --noconfirm --needed

# Software personal en flatpak
flatpak install -y \
com.github.KRTirtho.Spotube \
com.github.gabutakut.gabutdm \
com.github.iwalton3.jellyfin-media-player \
com.github.marktext.marktext \
com.github.tchx84.Flatseal \
com.google.EarthPro \
com.mattjakeman.ExtensionManager \
com.microsoft.Edge \
com.obsproject.Studio \
com.rustdesk.RustDesk \
com.spotify.Client \
com.valvesoftware.Steam \
com.vscodium.codium \
fr.handbrake.ghb \
io.github.celluloid_player.Celluloid \
io.github.peazip.PeaZip \
io.gitlab.adhami3310.Impression \
io.itch.itch \
io.missioncenter.MissionCenter \
io.mrarm.mcpelauncher \
net.brinkervii.grapejuice \
net.davidotek.pupgui2 \
net.minetest.Minetest \
org.audacityteam.Audacity \
org.gimp.GIMP \
org.gnome.Boxes \
org.gnome.Calculator \
org.gnome.Evince \
org.gnome.Loupe \
org.gnome.seahorse.Application  \
org.jdownloader.JDownloader \
org.kde.kdenlive \
org.libreoffice.LibreOffice \
org.mozilla.firefox \
org.pipewire.Helvum \
org.ryujinx.Ryujinx \
org.signal.Signal \
org.soundconverter.SoundConverter \
org.supertuxproject.SuperTux \
org.telegram.desktop


# para sacar la lista de apps:
# flatpak list --app --columns=application

# Mensaje final
printf '\n\n\tContribuye:\n\tmxhectorvega.com\n\n\n'
