#!/usr/bin/env bash

# Instalación de paquetes flatpak para el usuario doméstico.
# Repositorio: https://github.com/mxhectorvega/installarch
# Ejecución: curl -L is.gd/mxflatpak | bash
# Fecha de actualización: 04/02/2025
# Versión: 5.0

# Función para mostrar mensajes con formato
imprimir_mensaje() {
    local mensaje="$1"
    echo -e "\n\n\n\n\n\n\n\n\t\t\t\t\t\t\t$mensaje\n\n\n\n\n\n\n\n\n\n"
    sleep 3
}

# Verificar si flatpak está instalado, si no, instalarlo
if ! command -v flatpak &> /dev/null; then
    echo "Flatpak no está instalado. Instalándolo..."
    sudo pacman -S flatpak --noconfirm --needed
fi

# Agregar el repositorio flathub
if ! flatpak remote-list | grep -q flathub; then
    echo "Agregando el repositorio flathub..."
    flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo && flatpak -y update

fi

# Definir las listas de paquetes
paquetes_gnome=(
    "fr.handbrake.ghb"
    "app.drey.Dialect"
    "page.tesk.Refine"
    "org.gnome.Showtime"
    "net.davidotek.pupgui2"
    "net.minetest.Minetest"
    "net.supertuxkart.SuperTuxKart"
    "com.github.KRTirtho.Spotube"
    "com.github.gabutakut.gabutdm"
    "com.github.iwalton3.jellyfin-media-player"
    "com.github.tchx84.Flatseal"
    "com.github.neithern.g4music"
    "com.spotify.Client"
    "com.mattjakeman.ExtensionManager"
    "com.obsproject.Studio"
    "com.rustdesk.RustDesk"
    "com.valvesoftware.Steam"
    "com.brave.Browser"
    "io.github.peazip.PeaZip"
    "io.gitlab.adhami3310.Impression"
    "io.missioncenter.MissionCenter"
    "io.itch.itch"
    "io.mrarm.mcpelauncher"
    "org.gnome.Evolution"
    "org.gnome.Calculator"
    "org.gnome.Connections"
    "org.gnome.Evince"
    "org.gnome.Loupe"
    "org.gnome.TextEditor"
    "org.gnome.gitlab.YaLTeR.VideoTrimmer"
    "org.gnome.gitlab.somas.Apostrophe"
    "org.audacityteam.Audacity"
    "org.gimp.GIMP"
    "org.inkscape.Inkscape"
    "org.jdownloader.JDownloader"
    "org.kde.kdenlive"
    "org.kde.krita"
    "org.libreoffice.LibreOffice"
    "org.pipewire.Helvum"
    "org.signal.Signal"
    "org.soundconverter.SoundConverter"
    "org.supertuxproject.SuperTux"
    "org.telegram.desktop"
)

paquetes_kde=(
    "fr.handbrake.ghb"
    "net.davidotek.pupgui2"
    "net.minetest.Minetest"
    "net.supertuxkart.SuperTuxKart"
    "com.github.KRTirtho.Spotube"
    "com.github.iwalton3.jellyfin-media-player"
    "com.spotify.Client"
    "com.obsproject.Studio"
    "com.rustdesk.RustDesk"
    "com.valvesoftware.Steam"
    "com.brave.Browser"
    "io.github.peazip.PeaZip"
    "io.itch.itch"
    "io.mrarm.mcpelauncher"
    "org.kde.klevernotes"
    "org.kde.isoimagewriter"
    "org.kde.CrowTranslate"
    "org.rncbc.qpwgraph"
    "org.kde.gwenview"
    "org.kde.okular"
    "org.kde.kcalc"
    "org.kde.ktorrent"
    "org.kde.kontact"
    "org.audacityteam.Audacity"
    "org.gimp.GIMP"
    "org.inkscape.Inkscape"
    "org.jdownloader.JDownloader"
    "org.kde.kdenlive"
    "org.kde.krita"
    "org.libreoffice.LibreOffice"
    "org.signal.Signal"
    "org.supertuxproject.SuperTux"
    "org.telegram.desktop"
)

# Paquete adicional
paquete_adicional="https://sober.vinegarhq.org/sober.flatpakref"

# Bucle para preguntar al usuario hasta que seleccione una opción válida
while true; do
    echo "¿Qué lista de paquetes flatpak deseas instalar?"
    echo "1) Para entorno de escritorio GNOME (instalado con script minimal por mxhectorvega)"
    echo "2) Para entorno de escritorio KDE Plasma (instalado con archinstall desde archiso)"
    read -rp "Selecciona una opción (1 o 2): " opcion

    # Validar la opción seleccionada y proceder con la instalación
    if [ "$opcion" -eq 1 ]; then
        echo "Instalando paquetes de la Lista GNOME..."
        for paquete in "${paquetes_gnome[@]}"; do
            flatpak install --user -y "$paquete"
        done
        flatpak install --user -y "$paquete_adicional"
        break
    elif [ "$opcion" -eq 2 ]; then
        echo "Instalando paquetes de la Lista KDE..."
        for paquete in "${paquetes_kde[@]}"; do
            flatpak install --user -y "$paquete"
        done
        flatpak install --user -y "$paquete_adicional"
        echo "Instalando paquetes adicionales para permisos flatpak, capturador de pantalla y gestor de particiones GUI..."
        sudo pacman -Sy flatpak-kcm spectacle partitionmanager --noconfirm --needed
        break
    else
        echo "Opción no válida. Por favor, selecciona una opción válida."
    fi
done

# Mensaje final
imprimir_mensaje "♥️ Suscríbete!\n\n\t\t\t\t\t\t\t🌐 https://www.youtube.com/mxhectorvega"

# Comando para ver la lista de aplicaciones flatpak instaladas
# flatpak list --app --columns=application
