#!/usr/bin/env bash

# Instalación del entorno de escritorio Gnome 4.1.x minimal
# Repositorio: https://github.com/mxhectorvega/installarch
# Ejecución: bash <(curl -L is.gd/mxignome)
# Fecha de actualización: 07/02/2025
# Versión: 7.4

# Nota: El sistema debe haberse instalado preferentemente con la herramienta ArchInstall desde ArchISO seleccionando el perfil minimal (sin entorno de escritorio).

# Actualizar y sincronizar repositorios
sudo pacman -Sy --noconfirm

# Instalar paquetes esenciales para el sistema operativo
paquetes_esenciales=(
    "openssh"
    "seahorse"
    "acpi"
    "plocate"
    "usbutils"
    "ntfs-3g"
    "dosfstools"
    "flatpak"
    "pacman-contrib"
    "fuse"
    "xdg-user-dirs"
    "rsync"
    "nano"
)

sudo pacman -S "${paquetes_esenciales[@]}" --noconfirm --needed

# Instalar herramientas de terminal
herramientas_terminal=(
    "fastfetch"
    "git"
    "curl"
    "wget"
    "nvtop"
    "htop"
    "vim"
    "less"
    "man"
    "nmap"
    "speedtest-cli"
)

sudo pacman -S "${herramientas_terminal[@]}" --noconfirm --needed

# Instalar paquetes mínimos para que Gnome funcione
paquetes_gnome=(
    "gdm"
    "gnome-shell"
    "nautilus"
    "gnome-control-center"
    "gnome-software"
    "gnome-console"
    "gnome-disk-utility"
    "polkit-gnome"
    "xdg-desktop-portal"
    "xdg-desktop-portal-gnome"
)

sudo pacman -S "${paquetes_gnome[@]}" --noconfirm --needed

# Instalar el tema GTK3 de libadwaita
sudo pacman -S adw-gtk-theme --noconfirm --needed
flatpak install --user -y org.gtk.Gtk3theme.adw-gtk3 org.gtk.Gtk3theme.adw-gtk3-dark

# Crear directorios de usuario en español
xdg-user-dirs-update

# Crear enlace simbólico para el paquete ssh-askpass
sudo ln -s /usr/lib/seahorse/ssh-askpass /usr/lib/ssh/ssh-askpass

# Configurar ZRAM
sudo tee -a /etc/systemd/zram-generator.conf <<EOF
zram-size = ram
compression-algorithm = zstd
EOF

# Crear directorios de fuentes antes de clonar los repositorios
mkdir -p "$HOME/.local/share/fonts/tipografias"
mkdir -p "$HOME/.local/share/fonts/tipografiaswin"

# Clonar repositorios directamente en los directorios creados
git clone https://github.com/mxhectorvega/tipografias "$HOME/.local/share/fonts/tipografias"
git clone https://github.com/mxhectorvega/tipografiaswin "$HOME/.local/share/fonts/tipografiaswin"

# Limpiar archivos .git y .md
find "$HOME/.local/share/fonts/" -name ".git" -exec rm -rf {} +
find "$HOME/.local/share/fonts/" -name "*.md" -exec rm -f {} +

# Instalar y configurar el controlador de Bluetooth
sudo pacman -S bluez bluez-utils --needed --noconfirm
sudo systemctl enable --now bluetooth.service

# Instalar Java (por si acaso se requiere)
sudo pacman -S jre8-openjdk --noconfirm --needed

# Activar el servicio de pantalla de inicio de sesión (GDM)
for i in {1..8}; do
    clear
    printf 'Activando display manager'$(printf '.%.0s' $(seq 1 $i))
    sleep 0.1
done

sudo systemctl enable --now gdm
