#!/usr/bin/env bash

# Titulo: Instalación mínima del entorno de escritorio Gnome 4x.x consumiendo 400mb al inicio.
# Autor: Héctor Iván Vega Zamudio
# Correo: mxhectorvega@gmail.com
# Link: https://github.com/mxhectorvega/installarch
# Versión: 6.0
# Fecha de actualización 19/03/2023
# Nota: El sistema de preferencia debe haber sido instalado con la
# herramienta archinstall del liveUSB, seleccionando el perfil mínimo.

# Actualización
sudo pacman -Syyu --noconfirm

# Internos para el SO
sudo pacman -S usbutils ntfs-3g flatpak pacman-contrib xdg-user-dirs --noconfirm --needed
# Para ejecutar desde la terminal
sudo pacman -S git make gcc curl wget nvtop htop vim fuse less man --noconfirm --needed 

# Repo chaotic
sudo pacman -Syyu --noconfirm
sudo pacman-key --recv-key FBA220DFC880C036 --keyserver keyserver.ubuntu.com
sudo pacman-key --lsign-key FBA220DFC880C036
sudo pacman -U 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst' 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst' --noconfirm
sudo tee -a /etc/pacman.conf <<EOF
[chaotic-aur]
Include = /etc/pacman.d/chaotic-mirrorlist
EOF

# Paru
cd ; git clone https://aur.archlinux.org/paru-bin.git ; cd paru-bin ; makepkg -si --noconfirm ; cd ; rm -rf paru-bin
sudo sed -i "s/#BottomUp/BottomUp/g" /etc/paru.conf

# Actualización
sudo pacman -Syyu --noconfirm

# Paquetes mínimos para que Gnome funcione
sudo pacman -S gdm gnome-shell gnome-disk-utility gnome-terminal nautilus gnome-tweaks gnome-control-center gnome-software gnome-software-packagekit-plugin rtkit polkit-gnome qt5-wayland --noconfirm --needed
sudo pacman -S xdg-desktop-portal xdg-desktop-portal-gtk xdg-desktop-portal-gnome --noconfirm --needed
sudo pacman -S papirus-icon-theme adw-gtk3-git --noconfirm --needed
flatpak install -y org.gtk.Gtk3theme.adw-gtk3 org.gtk.Gtk3theme.adw-gtk3-dark

# Temas y fuentes mxhectorvega
git clone https://github.com/mxhectorvega/temas
git clone https://github.com/mxhectorvega/tipografias
cp -R $HOME/temas/.{icons,themes}/ $HOME
mkdir -p $HOME/.local/share/fonts
cp -R $HOME/tipografias "$HOME"/.local/share
rm -rf $HOME/tipografias
rm -rf $HOME/temas

# neofetch binario
sudo curl -s https://raw.githubusercontent.com/dylanaraps/neofetch/master/neofetch -o /usr/bin/neofetch
sudo chmod +x /usr/bin/neofetch

# Fuentes básicas
sudo pacman -S ttf-{dejavu,hack,roboto,liberation} terminus-font wqy-microhei unicode-character-database noto-fonts noto-fonts-cjk --noconfirm --needed

# habilitando bluetooth
sudo systemctl enable --now bluetooth.service

# crear directorios de usuario
xdg-user-dirs-update

# Mensaje final
sleep 1
printf '\n\n\tContribuye:\n\tmxhectorvega.ml\n\n\n'
sleep 1

# Habilitando servicio de pantalla de inicio de sesión
clear
printf '\n \nActivando display manager...\n'
sleep 1
sudo systemctl enable --now gdm
