#!/usr/bin/env bash

# Titulo: Instalación del gestor de ventanas Hyprland para wayland
# Link: https://github.com/mxhectorvega/installarch
# Versión: 4.5 01/04/2023
# Nota: El sistema de preferencia debe haber sido instalado con la
# herramienta archinstall del liveUSB, seleccionando el perfil mínimo.

# Actualización
sudo pacman -Syyu --noconfirm

# Internos para el SO
sudo pacman -S usbutils ntfs-3g flatpak pacman-contrib xdg-user-dirs --noconfirm --needed
# Para ejecutar desde la terminal
sudo pacman -S git make gcc curl wget nvtop htop vim fuse less imagemagick man --noconfirm --needed 

# Repo chaotic
sudo pacman -Syyu --noconfirm
sudo pacman-key --recv-key FBA220DFC880C036 --keyserver keyserver.ubuntu.com
sudo pacman-key --lsign-key FBA220DFC880C036
sudo pacman -U 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst' 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst' --noconfirm
sudo tee -a /etc/pacman.conf <<EOF
[chaotic-aur]
Include = /etc/pacman.d/chaotic-mirrorlist
EOF

# Paru
cd ; git clone https://aur.archlinux.org/paru-bin.git ; cd paru-bin ; makepkg -si --noconfirm ; cd ; rm -rf paru-bin
sudo sed -i "s/#BottomUp/BottomUp/g" /etc/paru.conf

# Actualización
sudo pacman -Syyu --noconfirm

# Software adicional
# Básicos
sudo pacman -S kitty thunar thunar-archive-plugin thunar-volman gvfs file-roller tumbler blueberry polkit-gnome --noconfirm --needed
# Visores de archivos
sudo pacman -S imv mpv zathura-pdf-mupdf --noconfirm --needed
# Utilidad para wallpapers en wyaland
sudo pacman -S swaybg-git --noconfirm --needed
# Control de volumen
sudo pacman -S pulsemixer --noconfirm --needed
# Gestor de redes wifi GTK
#network-manager-applet
# Portapapeles para wayland
sudo pacman -S clipman --noconfirm
# Habilitando servicio de bluetooth 
sudo systemctl enable --now bluetooth.service
# Utilidad para guardar contraseñas
sudo pacman -S gnome-keyring libsecret libgnome-keyring --noconfirm --needed
# Gestor de paquetes pacman GUI
paru -S pamac-all --noconfirm

# Hyprland
sudo pacman -S hyprland-git waybar-hyprland-git mako wofi --noconfirm --needed
sudo pacman -S qt5-wayland xorg-xwayland swayidle swaylock grim slurp wl-clipboard wf-ecorder brightnessctl --noconfirm --needed
sudo pacman -S xdg-desktop-portal xdg-desktop-portal-wlr --noconfirm --needed
sudo pacman -S wireplumber --noconfirm --needed

# Temas y fuentes mxhectorvega
git clone https://github.com/mxhectorvega/temas
git clone https://github.com/mxhectorvega/tipografias
cp -R $HOME/temas/.{icons,themes}/ $HOME
mkdir -p $HOME/.local/share/fonts
cp -R $HOME/tipografias "$HOME"/.local/share
rm -rf $HOME/tipografias
rm -rf $HOME/temas

# neofetch binario
sudo curl -s https://raw.githubusercontent.com/dylanaraps/neofetch/master/neofetch -o /usr/bin/neofetch
sudo chmod +x /usr/bin/neofetch

# Fuentes básicas
sudo pacman -S ttf-{dejavu,hack,roboto,liberation} terminus-font wqy-microhei unicode-character-database noto-fonts noto-fonts-cjk --noconfirm --needed

# ajustando VIM, HTOP y NVTOP para que los lanzadores.desktop funcionen con kitty
sudo sed -i "s/Exec=vim %F/Exec=kitty -e vim/g" /usr/share/applications/vim.desktop
sudo sed -i "s/Terminal=true/Terminal=false/g" /usr/share/applications/vim.desktop
sudo sed -i "s/Exec=htop/Exec=kitty -e htop/g" /usr/share/applications/htop.desktop
sudo sed -i "s/Terminal=true/Terminal=false/g" /usr/share/applications/htop.desktop
sudo sed -i "s/Exec=nvtop/Exec=kitty -e nvtop/g" /usr/share/applications/nvtop.desktop
sudo sed -i "s/Terminal=true/Terminal=false/g" /usr/share/applications/nvtop.desktop

# Mensaje final
sleep 1
printf '\n\n\tContribuye:\n\tmxhectorvega.ml\n\n\n'
sleep 1

# Habilitando servicio de pantalla de inicio de sesión
#clear
#printf '\n \nActivando display manager...\n'
#sleep 1
#sudo systemctl enable --now lightdm

#prueba1