#!/usr/bin/env bash

# Titulo: Instalación del gestor de ventanas Hyprland para wayland
# Autor: Hector Iván Vega Zamudio
# Correo: mxhectorvega@gmail.com
# Link: https://github.com/mxhectorvega
# Versión: v2.2
# Fecha de actualización 09/03/2023
# Nota: El sistema de preferencia debe haber sido instalado con la
# herramienta archinstall del liveUSB, seleccionando el perfil minimo.

# Actualizacion
sudo pacman -Syyu --noconfirm

# Repo chaotic
sudo pacman-key --recv-key FBA220DFC880C036 --keyserver keyserver.ubuntu.com
sudo pacman-key --lsign-key FBA220DFC880C036
sudo pacman -U 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst' 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst' --noconfirm
sudo tee -a /etc/pacman.conf <<EOF
[chaotic-aur]
Include = /etc/pacman.d/chaotic-mirrorlist
EOF

# Actualizacion
sudo pacman -Syyu --noconfirm

# Software adicional
sudo pacman -S git make gcc curl wget gnome-terminal nautilus make gcc htop vim blueberry pacman-contrib man bc polkit-gnome telegram-desktop imv mpv zathura-pdf-mupdf xdg-user-dirs python-pillow imagemagick usbutils ntfs-3g flatpak --noconfirm --needed
sudo pacman -S swaybg-git --noconfirm --needed
sudo pacman -S pulsemixer --noconfirm --needed
sudo pacman -S firefox --noconfirm --needed
# opcional agregar el gestor GTK de redes wifi
#network-manager-applet

# Paru
cd ; git clone https://aur.archlinux.org/paru-bin.git ; cd paru-bin ; makepkg -si --noconfirm ; cd ; rm -rf paru-bin
sudo sed -i "s/#BottomUp/BottomUp/g" /etc/paru.conf

# neofetch binario
sudo curl -s https://raw.githubusercontent.com/dylanaraps/neofetch/master/neofetch -o /usr/bin/neofetch
sudo chmod +x /usr/bin/neofetch

# Temas y fuentes mxhectorvega
git clone https://github.com/mxhectorvega/temas
git clone https://github.com/mxhectorvega/tipografias
cp -R $HOME/temas/.{icons,themes}/ $HOME
mkdir -p $HOME/.local/share/fonts
cp -R $HOME/tipografias "$HOME"/.local/share
rm -rf $HOME/tipografias
rm -rf $HOME/temas

# Hyprland
sudo pacman -S hyprland-git waybar-hyprland-git mako wofi --noconfirm --needed
sudo pacman -S rtkit qt5-wayland xorg-xwayland swayidle wofi mako waybar grim slurp wl-clipboard wf-recorder brightnessctl --noconfirm --needed
sudo pacman -S xdg-desktop-portal xdg-desktop-portal-gtk xdg-desktop-portal-wlr --noconfirm --needed
sudo pacman -S wireplumber --noconfirm --needed

# Fuentes basicas
sudo pacman -S ttf-{dejavu,hack,roboto,liberation} terminus-font wqy-microhei unicode-character-database noto-fonts noto-fonts-cjk --noconfirm --needed

# Display manager (pantalla de inicio de sesion)
# sudo pacman -S lightdm lightdm-gtk-greeter lightdm-gtk-greeter-settings --noconfirm

sudo pacman -S clipman --noconfirm

# Cambiando de fuente y wallpaper ligthDM
#sudo tee /etc/lightdm/lightdm-gtk-greeter.conf <<EOF
#[greeter]
#font-name=SF Compact Display 9
#xft-antialias=true
#xft-dpi=96
#xft-hintstyle=hintslight
#xft-rgba=rgb
#indicators=~session;~spacer;separator;~clock;~spacer;separator;~power;
#clock-format=%a, %b %d, %H:%M
#EOF

## Habilitando servicio de bluetooth 
sudo systemctl enable --now bluetooth.service

# Mensaje final
sleep 1
printf '\n\n\tContribuye:\n\tmxhectorvega.ml\n\n\n'
sleep 1
printf ''

