#!/usr/bin/env bash

# Titulo: Instalación del gestor de ventanas Hyprland para wayland
# Link: https://github.com/mxhectorvega/installarch
# Versión: 5.0 15/04/2023
# Nota: El sistema de preferencia debe haber sido instalado con la
# herramienta archinstall del liveUSB, seleccionando el perfil mínimo.

# Actualización
sudo pacman -Syyu --noconfirm

# Internos para el SO
sudo pacman -S usbutils ntfs-3g pacman-contrib xdg-user-dirs --noconfirm --needed

# Para ejecutar desde la terminal
sudo pacman -S git make gcc curl wget nvtop htop vim fuse less imagemagick man --noconfirm --needed 

# Básicos
sudo pacman -S kitty thunar thunar-archive-plugin thunar-volman gvfs file-roller tumbler blueberry polkit-gnome --noconfirm --needed

# Visores de archivos
sudo pacman -S imv mpv zathura-pdf-mupdf --noconfirm --needed

# Utilidad para wallpapers en wyaland
sudo pacman -S swaybg --noconfirm --needed

# Control de volumen
sudo pacman -S pulsemixer --noconfirm --needed

# Portapapeles para wayland
paru -S clipman --noconfirm --needed

# Habilitando servicio de bluetooth 
sudo systemctl enable --now bluetooth.service

# Utilidad para guardar contraseñas
sudo pacman -S gnome-keyring libsecret libgnome-keyring --noconfirm --needed

# Hyprland
sudo pacman -S sway waybar mako wofi --noconfirm --needed
sudo pacman -S qt5-wayland xorg-xwayland swayidle swaylock grim slurp wl-clipboard wf-recorder brightnessctl --noconfirm --needed
sudo pacman -S xdg-desktop-portal xdg-desktop-portal-wlr xdg-desktop-portal-gtk --noconfirm --needed
sudo pacman -S wireplumber --noconfirm --needed
paru -S hyprland wayfire --noconfirm --needed

# Temas y fuentes mxhectorvega
git clone https://github.com/mxhectorvega/temas
git clone https://github.com/mxhectorvega/tipografias
git clone https://github.com/mxhectorvega/hyprland
mkdir -p $HOME/.local/share/fonts
cp -R $HOME/temas/.{icons,themes}/ $HOME
cp -R $HOME/tipografias/ $HOME/.local/share/fonts/
cp -R $HOME/hyprland/.config/ $HOME
rm -rf $HOME/{tipografias,temas,hyprland}/

# Fuentes básicas
sudo pacman -S ttf-{dejavu,hack,roboto,liberation} terminus-font wqy-microhei unicode-character-database noto-fonts noto-fonts-cjk --noconfirm --needed

# ajustando VIM, HTOP y NVTOP para que los lanzadores.desktop funcionen con kitty
sudo sed -i "s/Exec=vim %F/Exec=kitty -e vim/g" /usr/share/applications/vim.desktop
sudo sed -i "s/Terminal=true/Terminal=false/g" /usr/share/applications/vim.desktop
sudo sed -i "s/Exec=htop/Exec=kitty -e htop/g" /usr/share/applications/htop.desktop
sudo sed -i "s/Terminal=true/Terminal=false/g" /usr/share/applications/htop.desktop
sudo sed -i "s/Exec=nvtop/Exec=kitty -e nvtop/g" /usr/share/applications/nvtop.desktop
sudo sed -i "s/Terminal=true/Terminal=false/g" /usr/share/applications/nvtop.desktop

# neofetch binario
sudo curl -s https://raw.githubusercontent.com/dylanaraps/neofetch/master/neofetch -o /usr/bin/neofetch
sudo chmod +x /usr/bin/neofetch

# Gestor de paquetes AUR GUI
paru -S pamac-aur-git --noconfirm --needed

# Mensaje final
sleep 1
printf '\n\n\tContribuye:\n\tmxhectorvega.ml\n\n\n'
