#!/usr/bin/env bash

# Instalacion de controladores para impresoras EPSON L3210 en Archlinux.
# Repositorio: https://github.com/mxhectorvega/installarch
# Ejecucion: bash <(curl -L is.gd/mximpresoras)
# Fecha de actualizacion: 04/02/2025
# Version: 3.1

# Actualizar
sudo pacman -Sy --noconfirm

# Instalar git
sudo pacman -S git --noconfirm --needed

# Clonar los controladores para impresoras Epson L3210 de un repositorio github
git clone https://github.com/razein97/Epson-L3210-Arch-Driver
cd Epson-L3210-Arch-Driver
makepkg -si

# Eliminar archivos clonados
rm -rf $HOME/Epson-L3210-Arch-Driver

# FIX problema con el filtro (se pone en pausa la impresion).
sudo ln -s /opt/epson-inkjet-printer-202101w/cups/lib/filter/epson_inkjet_printer_filter /usr/lib/cups/filter/epson_inkjet_printer_filter

# Instalar administrador de impresoras y establecer permisos en el sistema
sudo pacman -S system-config-printer cups --noconfirm --needed
sudo gpasswd -a $(whoami) sys
sudo gpasswd -a $(whoami) wheel
sudo gpasswd -a $(whoami) root
sudo gpasswd -a $(whoami) lp

# Iniciar los servicios de impresion
sudo systemctl enable --now cups

# Mensaje final
sleep 0.1
clear
sleep 0.1
printf '\n\n\n\n\n\n\n\n\t\t\t\t\t\t\t♥️ Suscríbete!\n\n\t\t\t\t\t\t\t🌐 https://www.youtube.com/mxhectorvega\n\n\n\n\n\n\n\n\n\n'
