#!/usr/bin/env bash

# Instalación y configuración de impresoras en Arch Linux.
# Repositorio: https://github.com/mxhectorvega/installarch
# Ejecución: bash <(curl -L is.gd/mximpresora)
# Fecha de actualización: 07/02/2025
# Versión: 5.2


# Actualizar y sincronizar repositorios
sudo pacman -Sy --noconfirm

# Instalar paquetes esenciales para la impresora
paquetes_impresora=(
    "system-config-printer"
    "cups"
    "cups-pdf"
)

sudo pacman -S "${paquetes_impresora[@]}" --noconfirm --needed

# Agregar el usuario al grupo de impresoras y otros grupos necesarios
sudo gpasswd -a "$USER" sys
sudo gpasswd -a "$USER" lp

# Iniciar y habilitar el servicio CUPS
sudo systemctl enable --now cups

# Verificar si git está instalado, si no, instalarlo
if ! command -v git &> /dev/null; then
    echo "git no está instalado. Instalándolo..."
    sudo pacman -S git --noconfirm --needed
fi

# Clonar los controladores para impresoras Epson L3210 de un repositorio github
echo "Clonando e instalando controladores Epson L3210..."
if git clone https://github.com/razein97/Epson-L3210-Arch-Driver; then
    cd Epson-L3210-Arch-Driver || exit
    if makepkg -si --noconfirm; then
        echo "Controladores instalados exitosamente."
    else
        echo "Error al instalar los controladores."
        exit 1
    fi
    cd ..
    rm -rf Epson-L3210-Arch-Driver
else
    echo "Error al clonar el repositorio."
    exit 1
fi

# FIX problema con el filtro (se pone en pausa la impresión).
if [ ! -f /usr/lib/cups/filter/epson_inkjet_printer_filter ]; then
    sudo ln -s /opt/epson-inkjet-printer-202101w/cups/lib/filter/epson_inkjet_printer_filter /usr/lib/cups/filter/epson_inkjet_printer_filter
    echo "Enlace simbólico para el filtro de impresión creado."
else
    echo "El enlace simbólico para el filtro de impresión ya existe."
fi

# Comando opcional para verificar el estado de los servicios de impresión
# sudo systemctl status cups
