#!/usr/bin/env bash

# Titulo: Instalacion automatica del software que uso en el dia a dia.
# Link: https://github.com/mxhectorvega/installarch
# Versión: 2.1 23/04/2023
# Nota: El sistema de preferencia debe haber sido instalado con la
# herramienta archinstall del liveUSB, seleccionando el perfil mínimo.

# Actualización
sudo pacman -Syyu --noconfirm

# Internos para el SO
sudo pacman -S usbutils ntfs-3g flatpak pacman-contrib xdg-user-dirs --noconfirm --needed

# Para ejecutar desde la terminal
sudo pacman -S git make gcc curl wget nvtop htop vim fuse less man --noconfirm --needed 

# Paru
cd ; git clone https://aur.archlinux.org/paru-bin.git ; cd paru-bin ; makepkg -si --noconfirm ; cd ; rm -rf paru-bin
sudo sed -i "s/#BottomUp/BottomUp/g" /etc/paru.conf

# Actualización
sudo pacman -Syyu --noconfirm

# instalando software KDE básico
sudo pacman -S sddm plasma konsole dolphin ark spectacle partitionmanager packagekit-qt5 --noconfirm --needed 

# Temas y fuentes mxhectorvega
git clone https://github.com/mxhectorvega/tipografias
mkdir -p $HOME/.local/share/fonts
cp -R $HOME/tipografias $HOME/.local/share/fonts
rm -rf $HOME/tipografias

# neofetch binario
sudo curl -s https://raw.githubusercontent.com/dylanaraps/neofetch/master/neofetch -o /usr/bin/neofetch
sudo chmod +x /usr/bin/neofetch

# Fuentes básicas
sudo pacman -S ttf-{dejavu,hack,roboto,liberation} terminus-font wqy-microhei unicode-character-database noto-fonts noto-fonts-cjk --noconfirm --needed

# Mensaje final
sleep 1
printf '\n\n\tContribuye:\n\tmxhectorvega.ml\n\n\n'
sleep 1

# Activar DSSM
clear
printf '\n \nActivando display manager...\n'
sleep 1
sudo systemctl enable --now sddm