#!/usr/bin/env bash

# Instalación mis configuraciones personales para KDE Plasma
# Repositorio: https://github.com/mxhectorvega/installarch
# Ejecución: bash <(curl -L is.gd/mxkde)
# Fecha de actualización: 07/02/2025
# Versión: 1.2

# Actualizar y sincronizar repositorios
sudo pacman -Sy --noconfirm

# Instalar paquetes esenciales para el sistema operativo
paquetes_esenciales=(
    "openssh"
    "acpi"
    "plocate"
    "usbutils"
    "ntfs-3g"
    "dosfstools"
    "flatpak"
    "pacman-contrib"
    "fuse"
    "xdg-user-dirs"
    "rsync"
    "nano"
)

sudo pacman -S "${paquetes_esenciales[@]}" --noconfirm --needed

# Instalar herramientas de terminal
herramientas_terminal=(
    "fastfetch"
    "git"
    "curl"
    "wget"
    "nvtop"
    "htop"
    "vim"
    "less"
    "man"
    "nmap"
    "speedtest-cli"
)

sudo pacman -S "${herramientas_terminal[@]}" --noconfirm --needed

# Paquetes faltantes en la instalacion KDE Plasma de archinstall
plasma=(
    "flatpak-kcm"
    "spectacle"
    "partitionmanager"
)

sudo pacman -S "${plasma[@]}" --noconfirm --needed

# Configurar ZRAM
sudo tee -a /etc/systemd/zram-generator.conf <<EOF
zram-size = ram
compression-algorithm = zstd
EOF

# Crear directorios de fuentes antes de clonar los repositorios
mkdir -p "$HOME/.local/share/fonts/tipografias"
mkdir -p "$HOME/.local/share/fonts/tipografiaswin"

# Clonar repositorios directamente en los directorios creados
git clone https://github.com/mxhectorvega/tipografias "$HOME/.local/share/fonts/tipografias"
git clone https://github.com/mxhectorvega/tipografiaswin "$HOME/.local/share/fonts/tipografiaswin"

# Limpiar archivos .git y .md
find "$HOME/.local/share/fonts/" -name ".git" -exec rm -rf {} +
find "$HOME/.local/share/fonts/" -name "*.md" -exec rm -f {} +

# Instalar y configurar el controlador de Bluetooth
sudo pacman -S bluez bluez-utils --needed --noconfirm
sudo systemctl enable --now bluetooth.service

# Instalar Java (por si acaso se requiere)
sudo pacman -S jre8-openjdk --noconfirm --needed

# Crear enlace simbólico para el paquete ssh-askpass
sudo ln -s /usr/bin/ksshaskpass /usr/lib/ssh/ssh-askpass

