#!/usr/bin/env bash

# Instalación mis configuraciones personales para KDE Plasma
# Repositorio: https://github.com/mxhectorvega/installarch
# Ejecución: curl -L is.gd/mxkde | bash
# Fecha de actualización: 05/02/2025
# Versión: 1.0

#!/usr/bin/env bash

# Instalación del entorno de escritorio Gnome 4.1.x minimal
# Repositorio: https://github.com/mxhectorvega/installarch
# Ejecución: curl -L is.gd/mxignome | bash
# Fecha de actualización: 04/02/2025
# Versión: 7.3

# Nota: El sistema debe haberse instalado preferentemente con la herramienta ArchInstall desde ArchISO seleccionando el perfil minimal (sin entorno de escritorio).

# Función para mostrar mensajes con formato
imprimir_mensaje() {
    local mensaje="$1"
    echo -e "\n\n\n\n\n\n\n\n\t\t\t\t\t\t\t$mensaje\n\n\n\n\n\n\n\n\n\n"
    sleep 3
}

# Actualizar y sincronizar repositorios
sudo pacman -Sy --noconfirm

# Instalar paquetes esenciales para el sistema operativo
paquetes_esenciales=(
    "openssh"
    "acpi"
    "plocate"
    "usbutils"
    "ntfs-3g"
    "dosfstools"
    "flatpak"
    "pacman-contrib"
    "fuse"
    "xdg-user-dirs"
    "rsync"
    "nano"
)

sudo pacman -S "${paquetes_esenciales[@]}" --noconfirm --needed

# Instalar herramientas de terminal
herramientas_terminal=(
    "fastfetch"
    "git"
    "curl"
    "wget"
    "nvtop"
    "htop"
    "vim"
    "less"
    "man"
    "nmap"
    "speedtest-cli"
)

sudo pacman -S "${herramientas_terminal[@]}" --noconfirm --needed

# Instalar administrador de impresoras y configurar permisos
sudo pacman -S system-config-printer cups --noconfirm --needed
sudo gpasswd -a "$(whoami)" sys
sudo gpasswd -a "$(whoami)" wheel
sudo gpasswd -a "$(whoami)" root
sudo gpasswd -a "$(whoami)" lp

# Iniciar el servicio de impresión
sudo systemctl enable --now cups

# Configurar ZRAM
sudo tee -a /etc/systemd/zram-generator.conf <<EOF
zram-size = ram
compression-algorithm = zstd
EOF

# Crear directorios de fuentes antes de clonar los repositorios
mkdir -p "$HOME/.local/share/fonts/tipografias"
mkdir -p "$HOME/.local/share/fonts/tipografiaswin"

# Clonar repositorios directamente en los directorios creados
git clone https://github.com/mxhectorvega/tipografias "$HOME/.local/share/fonts/tipografias"
git clone https://github.com/mxhectorvega/tipografiaswin "$HOME/.local/share/fonts/tipografiaswin"

# Limpiar archivos .git y .md
find "$HOME/.local/share/fonts/" -name ".git" -exec rm -rf {} +
find "$HOME/.local/share/fonts/" -name "*.md" -exec rm -f {} +

# Instalar y configurar el controlador de Bluetooth
sudo pacman -S bluez bluez-utils --needed --noconfirm
sudo systemctl enable --now bluetooth.service

# Instalar Java (por si acaso se requiere)
sudo pacman -S jre8-openjdk --noconfirm --needed

# Mensaje final
imprimir_mensaje "♥️ Suscríbete!\n\n\t\t\t\t\t\t\t🌐 https://www.youtube.com/mxhectorvega"

# Activar el servicio de pantalla de inicio de sesión (GDM)
for i in {1..8}; do
    clear
    printf 'Activando display manager'$(printf '.%.0s' $(seq 1 $i))
    sleep 0.1
done

sudo systemctl enable --now gdm
