#!/usr/bin/env bash

# Configuración de hardware y paquetes específicos para MacBook en Arch Linux.
# Repositorio: https://github.com/mxhectorvega/installarch
# Ejecución: bash <(curl -L is.gd/mxmacbook) o tinyurl.com/mxmacbook
# Fecha de actualización: 07/02/2025
# Versión: 5.0


# Actualizar y sincronizar repositorios
sudo pacman -Sy --noconfirm

# Instalar paquetes específicos para MacBook
paquetes_macbook=(
    "linux-headers"
    "broadcom-wl-dkms"
    "bluez"
    "bluez-utils"
)

sudo pacman -S "${paquetes_macbook[@]}" --noconfirm --needed

# Configuración del servicio de Bluetooth
sudo systemctl enable --now bluetooth.service
