#!/usr/bin/env bash

# Post instalacion de Archlinux Gnome para MacbookAIR2013 y MacbookPRO2011
# Fecha de actualizacion 11/11/2023

# Actualziacion
sudo pacman -Syyu --noconfirm

# Paquetes basicos
sudo pacman -S seahorse unrar openssh acpi plocate usbutils ntfs-3g exfatprogs dosfstools pacman-contrib git curl wget vim nano fastfetch htop flatpak less man --noconfirm --needed

# Fuentes y paquetes para descopresion dakata
sudo pacman -S unicode-character-database gnu-free-fonts wqy-microhei noto-fonts-emoji ttf-{inconsolata,dejavu,hack,roboto,liberation,fira-{sans,code},cascadia-code,nerd-fonts-symbols} hunspell-es_mx zip un{zip,rar,arj} arj cpio p{7zip,bzip2,igz} l{zop,zip,rzip,ha} --needed --noconfirm

# Compatibilidad con impresoras
sudo pacman -S system-config-printer --noconfirm --needed
sudo pacman -S cups --noconfirm --needed
sudo gpasswd -a $(whoami) sys
sudo gpasswd -a $(whoami) wheel
sudo gpasswd -a $(whoami) root
sudo gpasswd -a $(whoami) lp
sudo systemctl enable --now cups

# Paru AUR Helper
cd ; git clone https://aur.archlinux.org/paru-bin.git ; cd paru-bin ; makepkg -si --noconfirm ; cd ; rm -rf paru-bin
sudo sed -i "s/#BottomUp/BottomUp/g" /etc/paru.conf

# Actualziacion
sudo pacman -Syyu --noconfirm

# Paquetes de compatibilidad WIFI/WEBCAM MacBookPro 2011-2015 y MacBookAIR 2011-2017
sudo pacman -S dkms linux-headers broadcom-wl-dkms --noconfirm --needed

# Drivers impresora Epson L3210 multifuncional de tinta continua
paru -S epson-inkjet-printer-202101w --noconfirm --needed

# FIX para el driver oficial de impresora L3210
sudo ln -s /opt/epson-inkjet-printer-202101w/cups/lib/filter/epson_inkjet_printer_filter /usr/lib/cups/filter/epson_inkjet_printer_filter

# Firmware de webcam (facetime apple)
paru -S facetimehd-firmware --noconfirm --needed

# Chaotic-AUR - Automated building repo for AUR packages
sudo pacman-key --recv-key 3056513887B78AEB --keyserver keyserver.ubuntu.com
sudo pacman-key --lsign-key 3056513887B78AEB
sudo pacman -U 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst' 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst' --noconfirm

sudo tee -a /etc/pacman.conf <<EOF
[chaotic-aur]
Include = /etc/pacman.d/chaotic-mirrorlist
EOF

# Actualziacion
sudo pacman -Syyu --noconfirm

# Spotify sin publicidad (Chaotic REPO)
sudo pacman -S spotify-adblock-git --noconfirm --needed

# Gestor de software APPIMAGE
sudo pacman -S appimagelauncher --noconfirm --needed

# Preparador de USB booteable
sudo pacman -S ventoy-bin --noconfirm --needed

# Tema colloid
paru -S colloid-cursors-git colloid-gtk-theme-git colloid-icon-theme-git plasma5-themes-colloid-git --noconfirm --needed

# BlacBOX terminal 
sudo pacman -S blackbox-terminal --noconfirm --needed

# Remove gnome-console
sudo pacman -R gnome-console --noconfirm --needed

# Administrador de temas KDE para entornos GTK
sudo pacman -S kvantum --noconfirm --needed

# Descargar Minecraft Bedrock
wget https://github.com/minecraft-linux/appimage-builder/releases/download/v0.12.1-763/Minecraft_Bedrock_Launcher-x86_64-v0.12.1.763.AppImage

# Rustdesk visor de escritorio remoto escrito en RUST
wget https://github.com/rustdesk/rustdesk/releases/download/1.2.3/rustdesk-1.2.3-0-x86_64.pkg.tar.zst
sudo pacman -U rustdesk-1.2.3-0-x86_64.pkg.tar.zst --noconfirm

# Creando enlaces simbolicos para askpass package
sudo ln -s /usr/lib/seahorse/ssh-askpass /usr/lib/ssh/ssh-askpass --noconfirm --needed

# Software personal en flatpak
flatpak install -y \
com.github.KRTirtho.Spotube \
com.github.iwalton3.jellyfin-media-player \
com.github.tchx84.Flatseal \
com.google.Chrome \
com.mattjakeman.ExtensionManager \
com.obsproject.Studio \
com.valvesoftware.Steam \
fr.handbrake.ghb \
io.itch.itch \
net.brinkervii.grapejuice \
net.davidotek.pupgui2 \
net.minetest.Minetest \
org.audacityteam.Audacity \
org.fedoraproject.MediaWriter \
org.gimp.GIMP \
org.kde.kdenlive \
org.libreoffice.LibreOffice \
org.mozilla.Thunderbird \
org.pipewire.Helvum \
org.ryujinx.Ryujinx \
org.supertuxproject.SuperTux \
org.telegram.desktop \

# habilitando bluetooth
sudo systemctl enable --now bluetooth.service

# Ajustar temas para 
mkdir -p $HOME/.{themes,icons}/
cp -rf /usr/share/themes/* $HOME/.themes
cp -rf /usr/share/icons/* $HOME/.icons
sudo flatpak override --filesystem=$HOME/.themes
sudo flatpak override --filesystem=$HOME/.icons
sudo flatpak override --filesystem=xdg-config/gtk-2.0:ro
sudo flatpak override --filesystem=xdg-config/gtk-3.0:ro
sudo flatpak override --filesystem=xdg-config/gtk-4.0:ro
rm -rf .config/gtk-*
cp -rf "$HOME/.themes/$(dconf read /org/gnome/desktop/interface/gtk-theme | tr -d "''")/gtk-2.0" "$HOME/.config/"
cp -rf "$HOME/.themes/$(dconf read /org/gnome/desktop/interface/gtk-theme | tr -d "''")/gtk-3.0" "$HOME/.config/"
cp -rf "$HOME/.themes/$(dconf read /org/gnome/desktop/interface/gtk-theme | tr -d "''")/gtk-4.0" "$HOME/.config/"

# Fuentes mxhectorvega
cd $HOME
mkdir -p $HOME/.local/share/fonts
cd $HOME
git clone https://github.com/mxhectorvega/tipografias
git clone https://github.com/mxhectorvega/tipografiaswin
cp -R $HOME/tipografias "$HOME"/.local/share/fonts
cp -R $HOME/tipografiaswin "$HOME"/.local/share/fonts
sleep 1
cd $HOME
rm -rf $HOME/tipografias
rm -rf $HOME/tipografiaswin

# Activando SSH para acceso remoto
sudo systemctl enable --now sshd

# Mensaje final
printf '\n\n\tContribuye:\n\tmxhectorvega.com\n\n\n'


