#!/usr/bin/env bash

# Instalacion de drivers para MacBookPro 2011-2015 y MacBookAIR 2011-2017 en Archlinux
# Repositorio: https://github.com/mxhectorvega/installarch
# Ejecucion: bash <(curl -L is.gd/mxmacbook)
# Fecha de actualización 04/02/2025
# Versión: 1.9

# Actualziacion
sudo pacman -Sy --noconfirm

# Paquetes de compatibilidad WIFI MacBookPro 2011-2015 y MacBookAIR 2011-2017
sudo pacman -S dkms linux-headers broadcom-wl-dkms --noconfirm --needed

# Drivers para bluetooth
sudo pacman -S bluez{,-utils} --needed --noconfirm

# habilitando bluetooth
sudo systemctl enable --now bluetooth.service

# Mensaje final
sleep 0.1
clear
sleep 0.1
printf '\n\n\n\n\n\n\n\n\t\t\t\t\t\t\t♥️ Suscríbete!\n\n\t\t\t\t\t\t\t🌐 https://www.youtube.com/mxhectorvega\n\n\n\n\n\n\n\n\n\n'
sleep 3
