#!/usr/bin/env bash

# Titulo: Instalación mínima del gestor de ventanas i3
# Autor: Hector Iván Vega Zamudio
# Correo: mxhectorvega@gmail.com
# Link: https://github.com/mxhectorvega
# Versión:v1.0
# fecha de actualización 12/06/2022
# Nota: El sistema de preferencia tuvo que haber sido instalado con la herramienta archinstall del liveUSB,
# Seleccionando el perfil Xorg con todos los controladores de código abierto.

# -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-* 
# Pacman configuraciones
# -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-* 
clear 
echo "\

Configurando gestor de paquetes Pacman..." 
sleep 1
sudo sed -i "s/#Color/Color/g" /etc/pacman.conf 
sudo sed -i "s/#ParallelDownloads/ParallelDownloads/g" /etc/pacman.conf
sudo sed -i "38i ILoveCandy" /etc/pacman.conf


# -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-* 
# Paquetes adicionales
# -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-* 
clear
echo "\

Instalando paquetes adicionales..."
sleep 1
sudo pacman -S sxiv mupdf zathura feh dmenu lightdm i3 i3blocks kitty file-roller git vlc neofetch firefox telegram-desktop geany htop bpytop ranger neovim cowsay lolcat figlet gcc make xdg-user-dirs gvfs thunar-volman network-manager-applet --noconfirm --needed
sudo pacman -S ttf-{dejavu,hack,roboto,liberation} wqy-microhei bdf-unifont unicode-character-database noto-fonts-emoji --noconfirm
sudo systemctl enable lightdm

sudo pacman -S xsetroot --noconfirm --needed
sudo pacman -S xrdb --noconfirm --needed
sudo pacman -S xprop --noconfirm --needed



# -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-* 
# Paru AUR helper
# -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-* 
clear 
echo "\

Instalando el gestor de paquetes Paru..." 
sleep 1
cd ; git clone https://aur.archlinux.org/paru-bin.git ; cd paru-bin ; makepkg -si --noconfirm ; cd ; rm -rf paru-bin



# -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-* 
# Dotfiles
# -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-* 
clear
echo "\
 
Copiando prompt, fuentes, scripts y configuraciones..."
sleep 1
git clone https://github.com/mxhectorvega/dotfilesarchlinux /tmp/dots
sudo rm -rf ~/.bashrc
mkdir ~/.local/bin
mkdir ~/.local/share/fonts
cp -R /tmp/dots/.config/* ~/.config
cp -R /tmp/dots/.local/bin/* ~/.local/bin
cp -R /tmp/dots/.local/share/fonts/* ~/.local/share/fonts
cp /tmp/dots/.bashrc ~/.bashrc


