#!/bin/bash 

clear 
echo "" 
echo "" 
echo "Configurando gestor de paquetes Pacman..." 
sleep 2 
#sed -i "s/#Color/Color/" /etc/pacman.conf 
#sed -i "s/#TotalDownload/TotalDownload/" /etc/pacman.conf 
#sed -i "s/#VerbosePkgLists/VerbosePkgLists/" /etc/pacman.conf 
#sed -i "37i ILoveCandy" /etc/pacman.conf 
#sed -i "s/#[multilib]/[multilib]/" /etc/pacman.conf 
sed -i "s/#ParallelDownloads/ParallelDownloads/" /etc/pacman.conf
#sed -i "s/#Include = /etc/pacman.d/mirrorlist/Include = /etc/pacman.d/mirrorlist/" /etc/pacman.conf
  
clear 
echo "" 
echo "" 
echo "Instalando el gestor de paquetes Paru..." 
sleep 2 
cd ; git clone https://aur.archlinux.org/paru-bin.git ; cd paru-bin ; makepkg -si --noconfirm ; cd ; rm -rf paru-bin
# sed -i "82c %wheel ALL=(ALL) ALL"  /mnt/etc/sudoers

clear
echo "" 
echo "" 
echo -e "Copiando prompt, fuentes, scripts y configuraciones..."
sleep 2 
sudo rm -rf ~/.bashrc
mkdir ~/.local/bin
mkdir ~/.local/share/fonts
git clone https://github.com/mxhectorvega/dotfilesarchlinux /tmp/dots
cp -R /tmp/dots/.config/* ~/.config
cp -R /tmp/dots/.local/bin/* ~/.local/bin
cp -R /tmp/dots/.local/share/fonts/* ~/.local/share/fonts
