#!/usr/bin/env bash

# Instalación de Paru y configuración del repositorio Chaotic AUR en Arch Linux.
# Repositorio: https://github.com/mxhectorvega/installarch
# Ejecución: bash <(curl -L is.gd/mxrepos)
# Fecha de actualización: 07/02/2025
# Versión: 5.1

imprimir_mensaje() {
    local mensaje="$1"
    echo -e "$mensaje"
    sleep 3
}


# Verificar permisos de sudo
if ! sudo -v; then
    imprimir_mensaje "Este script requiere permisos de sudo. Ejecútalo como root o con un usuario con permisos de sudo."
    exit 1
fi

# Actualizar y sincronizar repositorios
echo "Actualizando repositorios..."
sudo pacman -Sy --noconfirm || { imprimir_mensaje "Error al actualizar repositorios."; exit 1; }

# Verificar e instalar dependencias
for dep in git wget; do
    if ! command -v "$dep" &> /dev/null; then
        echo "Instalando $dep..."
        sudo pacman -S "$dep" --noconfirm --needed || { imprimir_mensaje "Error al instalar $dep."; exit 1; }
    fi
done

# Instalar Paru, AUR helper
if ! command -v paru &> /dev/null; then
    echo "Instalando Paru, AUR helper..."
    sudo pacman -S --needed --noconfirm base-devel || { imprimir_mensaje "Error al instalar base-devel."; exit 1; }

    # Clonar paru-bin en lugar de paru
    echo "Clonando paru-bin desde AUR..."
    git clone https://aur.archlinux.org/paru-bin.git || { imprimir_mensaje "Error al clonar el repositorio de paru-bin."; exit 1; }

    # Compilar e instalar paru-bin
    echo "Compilando e instalando paru-bin..."
    cd paru-bin || exit
    makepkg -si --noconfirm || { imprimir_mensaje "Error al compilar paru-bin."; exit 1; }
    cd ..

    # Eliminar el directorio clonado
    echo "Limpiando archivos temporales..."
    rm -rf paru-bin
fi

# Configurar repositorio Chaotic AUR
echo "Configurando el repositorio Chaotic AUR..."

# Recepción y firma de la clave
if ! sudo pacman-key --recv-key 3056513887B78AEB --keyserver keyserver.ubuntu.com; then
    imprimir_mensaje "Error al recibir la clave. Verifica tu conexión a Internet."
    exit 1
fi
if ! sudo pacman-key --lsign-key 3056513887B78AEB; then
    imprimir_mensaje "Error al firmar la clave."
    exit 1
fi

# Descargar e instalar paquetes de clave y lista de espejos
wget https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst || { imprimir_mensaje "Error al descargar chaotic-keyring."; exit 1; }
wget https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst || { imprimir_mensaje "Error al descargar chaotic-mirrorlist."; exit 1; }
sudo pacman -U chaotic-keyring.pkg.tar.zst --noconfirm || { imprimir_mensaje "Error al instalar chaotic-keyring."; exit 1; }
sudo pacman -U chaotic-mirrorlist.pkg.tar.zst --noconfirm || { imprimir_mensaje "Error al instalar chaotic-mirrorlist."; exit 1; }

# Eliminar archivos descargados
rm chaotic-keyring.pkg.tar.zst chaotic-mirrorlist.pkg.tar.zst

# Añadir el repositorio Chaotic AUR al archivo /etc/pacman.conf
echo "Añadiendo repositorio Chaotic AUR a /etc/pacman.conf..."
sudo tee -a /etc/pacman.conf <<EOF

[chaotic-aur]
SigLevel = PackageRequired
Server = https://geo-mirror.chaotic.cx/\$repo/\$arch
EOF

# Optimizar el gestor de paquetes pacman
echo "Optimizando el gestor de paquetes pacman..."
sudo sed -i 's/^#ParallelDownloads.*$/ParallelDownloads = 25/' /etc/pacman.conf
sudo sed -i 's/^#Color/Color/' /etc/pacman.conf

# Añadir la línea ILoveCandy si no existe
if ! grep -q "^ILoveCandy" /etc/pacman.conf; then
    sudo sed -i '/^# Misc options/a ILoveCandy' /etc/pacman.conf
    echo "La línea 'ILoveCandy' ha sido añadida a /etc/pacman.conf."
else
    echo "La línea 'ILoveCandy' ya existe en /etc/pacman.conf."
fi

# Optimizar el gestor de paquetes paru
echo "Optimizando el gestor de paquetes paru..."
sudo sed -i 's/#BottomUp/BottomUp/g' /etc/paru.conf
sudo sed -i 's/^#AurTimeout.*$/AurTimeout = 300/' /etc/paru.conf

# Actualizar el sistema con el nuevo repositorio
echo "Actualizando el sistema..."
sudo pacman -Syyu --noconfirm || { imprimir_mensaje "Error al actualizar el sistema."; exit 1; }
