#!/usr/bin/env bash

## Titulo: Instalación automática del software que uso en el día a día.
# Link: https://github.com/mxhectorvega/installarch
## Versión: 8.0 15/04/2023
# Nota: El sistema de preferencia debe haber sido instalado con la
# herramienta archinstall del liveUSB, seleccionando el perfil mínimo.

# Actualización
sudo pacman -Syyu --noconfirm

# Software de repositorios oficiales
sudo pacman -S obs-studio gimp kdenlive inkscape audacity steam libreoffice-fresh-es gnome-disk-utility supertux supertuxkart gcompris-qt --noconfirm --needed

# Software de repositorios oficiales
paru -S vscodium-bin microsoft-edge-stable-bin appimagelauncher ventoy-bin protonup-git spotify --noconfirm --needed

# SERVER
sudo pacman -S cockpit-podman --noconfirm --needed

# WINE
sudo pacman -Syu wine gnutls lib32-gnutls libpulse lib32-libpulse --noconfirm --needed

# ROBLOX
git clone --depth=1 https://aur.archlinux.org/grapejuice-git.git /tmp/grapejuice-git
cd /tmp/grapejuice-git
makepkg -si

# Mensaje final
sleep 1
printf '\n\n\tContribuye:\n\tmxhectorvega.ml\n\n\n'
sleep 1
printf ''

