#!/usr/bin/env bash

# Titulo: Post-install para Sway en Archlinux
# Autor: Héctor Iván Vega Zamudio
# Correo: mxhectorvega@gmail.com
# Link: https://github.com/mxhectorvega/installarch
# Versión: 9.1
# Fecha de actualización 19/03/2023
# Nota: El sistema de preferencia debe haber sido instalado con la
# herramienta archinstall del liveUSB, seleccionando el perfil mínimo.

# Actualización
sudo pacman -Syyu --noconfirm

# Internos para el SO
sudo pacman -S usbutils ntfs-3g flatpak pacman-contrib xdg-user-dirs --noconfirm --needed
# Para ejecutar desde la terminal
sudo pacman -S git make gcc curl wget htop vim fuse less man --noconfirm --needed 

# Repo chaotic
sudo pacman -Syyu --noconfirm
sudo pacman-key --recv-key FBA220DFC880C036 --keyserver keyserver.ubuntu.com
sudo pacman-key --lsign-key FBA220DFC880C036
sudo pacman -U 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst' 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst' --noconfirm
sudo tee -a /etc/pacman.conf <<EOF
[chaotic-aur]
Include = /etc/pacman.d/chaotic-mirrorlist
EOF

# Paru
cd ; git clone https://aur.archlinux.org/paru-bin.git ; cd paru-bin ; makepkg -si --noconfirm ; cd ; rm -rf paru-bin
sudo sed -i "s/#BottomUp/BottomUp/g" /etc/paru.conf

# Actualización
sudo pacman -Syyu --noconfirm

# Temas y fuentes mxhectorvega
git clone https://github.com/mxhectorvega/temas
git clone https://github.com/mxhectorvega/tipografias
git clone https://github.com/mxhectorvega/sway-arch
cp -R $HOME/temas/.{icons,themes}/ $HOME
mkdir -p $HOME/.local/share/fonts
cp -R $HOME/tipografias "$HOME"/.local/share
cp -rf $HOME/sway-arch/.config/ "$HOME"
rm -rf "$HOME"/{sway-arch,tipografias,temas}/

# Software adicional
sudo pacman -S git kitty make gcc htop vim blueberry network-manager-applet pacman-contrib man bc polkit-gnome telegram-desktop imv mpv zathura-pdf-mupdf mousepad xdg-user-dirs python-pillow imagemagick --noconfirm --needed

# SwayWM
sudo pacman -S sway --noconfirm --needed
sudo pacman -S rtkit qt5-wayland xorg-xwayland swayidle wofi mako waybar grim slurp wl-clipboard wf-recorder brightnessctl --noconfirm --needed
sudo pacman -S xdg-desktop-portal xdg-desktop-portal-gtk xdg-desktop-portal-wlr --noconfirm --needed
sudo pacman -S wireplumber --noconfirm --needed

# Thunar extras
sudo pacman -S gvfs thunar thunar-archive-plugin thunar-volman thunar-archive-plugin tumbler ffmpegthumbnailer xarchiver zip unzip unrar unarj p7zip lzop lzip lrzip lha cpio arj --noconfirm --needed

# Display manager (pantalla de inicio de sesion)
sudo pacman -S lightdm lightdm-gtk-greeter lightdm-gtk-greeter-settings --noconfirm

# Portapapeles para wayland
sudo pacman -S clipman --noconfirm

# Desinstalar terminal y menu obsoletos
clear
sudo pacman -Rs dmenu --noconfirm
sudo pacman -Rs alacritty --noconfirm
sudo pacman -Rs nano --noconfirm
sudo pacman -Rs foot --noconfirm

## Habilitando servicio de bluetooth 
sudo systemctl enable --now bluetooth.service

# Mensaje final
sleep 1
printf '\n\n\tContribuye:\n\tmxhectorvega.ml\n\n\n'
sleep 1

# Habilitando servicio de pantalla de inicio de sesión
clear
printf '\n \nActivando display manager...\n'
sleep 1
sudo systemctl enable --now lightdm

